version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1'
    ]
    environment:
      MYSQL_DATABASE: purple
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
