version: '3.8'
services:
  spring:
    image: public.ecr.aws/${ECR_REGISTRY_ALIAS}/purple-ecr:${VERSION:-latest}
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - VERSION=${VERSION:-latest}
    pull_policy: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: purple
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.4
    container_name: redis_dev
    ports:
      - "6379:6379"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: es
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_USERNAME=purple
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-bridge

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge


volumes:
  mysql-volume:
