server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/purple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true

  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      s3:
        bucket: perpicks-2024
      region:
        static: ap-northeast-2
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

auth:
  jwt:
    issuer: ${JWT_ISSUER:purple}
    access:
      expire-seconds: ${JWT_ACCESS_EXPIRE_SECONDS:172800}
      secret: ${JWT_ACCESS_SECRET:secret}

    refresh:
      expire-seconds: ${JWT_REFRESH_EXPIRE_SECONDS:1209600}
      secret: ${JWT_REFRESH_SECRET:secret}

    jwt:
      expire-seconds: ${JWT_EXPIRE_SECONDS:172800}
      secret: ${JWT_SECRET:secret}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    response-type: code
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: ${KAKAO_REDIRECT_URI:/auth/login/kakao}
    jwks-uri: ${KAKAO_JWKS_URI:https://kauth.kakao.com/.well-known/jwks.json}

uri:
  server: ${SERVER_URI:http://localhost:8080}
  client: ${CLIENT_URI:http://localhost:3000}
  server-complaint: ${SERVER_COMPLAINT_URI:http://localhost:8080/perpicks/complaints}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  docker:
    compose:
      file: ./compose-local.yaml

scheduler:
  daily-cron: 0 0 * * * *

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  docker:
    compose:
      enabled: false

scheduler:
  daily-cron: 0 0 3 * * *
