server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/purple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}

    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

auth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    response-type: code
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    token-request-uri: https://kauth.kakao.com/oauth/token
    redirect-uri: http://localhost:3000/redirect_url
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  docker:
    compose:
      file: ./compose-local.yaml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  docker:
    compose:
      enabled: false
